version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /desktop/src-tauri
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
